#!/bin/bash

up () {
  ssh loja@127.0.0.1 "cd /var/www/html && composer install && npm install && npm run build && php bin/console doctrine:database:create && php bin/console doctrine:migrations:migrate"
}

$1 $2 $3  